openapi: 3.0.0
info:
  title: File Upload API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload a CSV file
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      x-swagger-router-controller: uploadController
      x-swagger-router-models: false
